spring.application.name=task-manager
# SQLite
spring.datasource.url=jdbc:sqlite:taskmanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# JWT
# Hypersistence Utils
hypersistence.utils.jackson.object.mapper=com.taskmanager.config.SFObjectMapper
# JWT
jwt.secret=${JWT_SECRET:YOU_MUST_CHANGE_THIS_SECRET_KEY_IN_PRODUCTION_MIN_256_BITS_LONG_HERE}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000
